package com.arise.habitquest.e2e.support

object E2ESelectors {
    const val ONBOARDING_NEXT = "onboarding_next"
    const val ONBOARDING_BACK = "onboarding_back"
    const val REGISTRATION_COMPLETE_SCREEN = "registration_complete_screen"
    const val REGISTRATION_COMPLETE_ENTER = "registration_complete_enter"
    const val MISSION_DETAIL_SCREEN = "mission_detail_screen"
    const val MISSION_DETAIL_COMPLETE = "mission_detail_complete"
    const val MISSION_DETAIL_FAIL = "mission_detail_fail"
    const val MISSION_COMPLETE_SCREEN = "mission_complete_screen"
    const val MISSION_COMPLETE_RETURN = "mission_complete_return"
    const val RANKUP_SCREEN = "rankup_screen"
    const val RANKUP_CONTINUE = "rankup_continue"

    const val BOTTOM_NAV_HOME = "bottom_nav_home"
    const val BOTTOM_NAV_MISSIONS = "bottom_nav_missions"
    const val BOTTOM_NAV_STATUS = "bottom_nav_status"
    const val BOTTOM_NAV_AWARDS = "bottom_nav_awards"

    const val STATUS_SCREEN = "status_screen"
    const val STATUS_RANK_LEVEL = "status_rank_level"
    const val STATUS_TOTAL_MISSIONS = "status_total_missions"
    const val STATUS_TOTAL_XP_EARNED = "status_total_xp_earned"
    const val STATUS_CURRENT_STREAK = "status_current_streak"
    const val STATUS_BEST_STREAK = "status_best_streak"
    const val STATUS_VIEW_ACHIEVEMENTS = "status_view_achievements"
    const val STATUS_VIEW_HISTORY = "status_view_history"

    const val HOME_SETTINGS_BUTTON = "home_settings_button"
    const val SETTINGS_SCREEN = "settings_screen"
    const val SETTINGS_REGENERATE_BUTTON = "settings_regenerate_button"
    const val SETTINGS_REGENERATE_DIALOG = "settings_regenerate_dialog"
    const val SETTINGS_REGENERATE_CANCEL = "settings_regenerate_cancel"
    const val SETTINGS_REGENERATE_CONFIRM = "settings_regenerate_confirm"
    const val SETTINGS_STASIS_BUTTON = "settings_stasis_button"
    const val SETTINGS_STASIS_USES = "settings_stasis_uses"
    const val SETTINGS_NOTIFICATION_LABEL = "settings_notification_label"
    const val SETTINGS_FOCUS_COUNT = "settings_focus_count"
    const val SETTINGS_NOTIFICATION_SLIDER = "settings_notification_slider"

    const val ACHIEVEMENT_SCREEN = "achievement_screen"
    const val ACHIEVEMENT_SUMMARY = "achievement_summary"
    const val ACHIEVEMENT_DETAIL_DIALOG = "achievement_detail_dialog"

    const val HISTORY_SCREEN = "history_screen"
    const val HISTORY_SUMMARY_ROW = "history_summary_row"
    const val HISTORY_SUMMARY_MISSIONS = "history_summary_missions"
    const val HISTORY_SUMMARY_XP = "history_summary_xp"
    const val HISTORY_SUMMARY_STREAK = "history_summary_streak"
    const val HISTORY_HEATMAP = "history_heatmap"
    const val HISTORY_WEEKLY_XP_CHART = "history_weekly_xp_chart"
    const val HISTORY_EMPTY_STATE = "history_empty_state"

    const val MISSIONS_TAB_ROW = "missions_tab_row"
    const val MISSIONS_PAGER = "missions_pager"

    fun onboardingPhase(index: Int): String = "onboarding_phase_$index"
    fun missionCard(id: String): String = "mission_card_$id"
    fun missionQuickComplete(id: String): String = "mission_quick_complete_$id"
    fun missionReset(id: String): String = "mission_reset_$id"
    fun missionStatusCompleted(id: String): String = "mission_status_completed_$id"
    fun missionStatusFailed(id: String): String = "mission_status_failed_$id"
    fun missionsTab(index: Int): String = "missions_tab_$index"
    fun missionsListPage(index: Int): String = "missions_list_page_$index"
    fun achievementFilter(name: String): String = "achievement_filter_${name.lowercase()}"
    fun achievementCard(id: String): String = "achievement_card_$id"
    fun historyInsight(index: Int): String = "history_insight_$index"
    fun settingsRestDay(dayNameLowercase: String): String = "settings_rest_day_${dayNameLowercase}"
    fun settingsRestDaySelected(dayNameLowercase: String): String = "settings_rest_day_selected_${dayNameLowercase}"
}
